<?php

namespace Spiderwisp\LaravelOverlord\Enums;

enum AiErrorCode: string
{
	case QUOTA_EXCEEDED = 'QUOTA_EXCEEDED';
	case RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
	case INVALID_API_KEY = 'INVALID_API_KEY';
	case INVALID_SIGNATURE = 'INVALID_SIGNATURE';
	case DECRYPTION_ERROR = 'DECRYPTION_ERROR';
	case SAAS_ERROR = 'SAAS_ERROR';
	case VALIDATION_FAILED = 'VALIDATION_FAILED';
	case INVALID_RESPONSE = 'INVALID_RESPONSE';
}